### ISSUE TITLE
install(dataset, "sqlite") discards downloaded data?

### ISSUE THREAD

**Issue by davharris** [ropensci/ecoretriever#50]
When the connection is to an sqlite database and `db_file` is null (the default), the user doesn't have any easy way to access the data after it's done downloading.

```r
x = ecoretriever::install("mcdb", "sqlite")
x  # returns 0
```
It also doesn't seem to save the data anywhere in my working directory. (**Edit:** looks like it downloaded the data to the default location I set in the GUI a while back)

The issue seems to occur [here](https://github.com/ropensci/ecoretriever/blob/master/R/ecoretriever.R#L48-L49) in the source code:

```r
    if (is.null(db_file))
      cmd = paste('retriever install', connection, dataset)
```

As a user, I'd prefer a warning or an error when `db_file` is missing.

**Comment by davharris** [comment]
Okay, it looks like it's just sending the data to my default database, which is reasonable.  But maybe it should print a message when it does this, so that the user doesn't look for it in their working directory?

**Comment by ethanwhite** [comment]
Hmm, this behavior is a little surprising to me.

In the GUI the Retriever should do the following:

1. Check to see if you've specified a path in the call and use that path
2. If not, check to see if there is a stored version (whatever you used last) in `~/.retriever/connections.config` and use that path
3. If neither of these it will store to the default directory `.` using the default file name, which is `sqlite.db`for the SQLite engine.

But step 2 should only occur in the GUI and therefore your commands should result in the database being installed in `sqlite.db` in your working directory.

A local test with a different path stored in `connections.config` results in the expected behavior for me.

Can you try this same thing using the CLI to see what the behavior is? Just make an empty directory and run `retriever install sqlite mcdb` and see if the database ends up in `sqlite.db` in that directory.

Thanks for reporting!

**Comment by davharris** [comment]
Looks like it also shows up in the default directory rather than my working directory.

Here's what happens when I run your command in my mistnet directory:

```
Macintosh-3:mistnet davidjharris$ retriever install sqlite mcdb
=> Installing Mammal Community DataBase (Ecological Archives 2011)
Creating table MCDB_communities...
Inserting rows to MCDB_communities: 7977 / 7977
Creating table MCDB_species...
Inserting rows to MCDB_species: 700 / 700
Creating table MCDB_references...
Inserting rows to MCDB_references: 186 / 186
Creating table MCDB_trapping...
Inserting rows to MCDB_trapping: 1169 / 1169
Creating table MCDB_sites...
Inserting rows to MCDB_sites: 1000 / 1000
Done!
Macintosh-3:mistnet davidjharris$ ls
AllBirdsEricson1.tre	README.md		mistnet.Rproj
DESCRIPTION		extras			vignettes
NAMESPACE		inst			wc10
R			man
```
I don't see it there.

Meanwhile, when I check the sqlite.db file on my desktop, it says that it was updated one minute ago.

I think this is because my ~/.retriever/connections.config file is `SQLite,{'table_name': '{db}_{table}', 'file': '/Users/davidjharris/Desktop/sqlite.db'}`.  I must have set that in the GUI when I first installed retriever.

So I think `retriever` is doing what I told it to, but I still think that the R interface should probably report in some way that it's saving things in the default directory rather than the working directory.

**Comment by ethanwhite** [comment]
> So I think retriever is doing what I told it to, but I still think that the R interface should probably report in some way that it's saving things in the default directory rather than the working directory.

I don't think this is actually the expected behavior. When I did the same thing locally I got the opposite result and if you look at the code that looks at `connections.config` it only runs when running the GUI.

Are you running on Windows?

**Comment by davharris** [comment]
Mac.  I installed retriever as part of a full package including the GUI, though.  Maybe that’s what’s going on?

**Comment by ethanwhite** [comment]
> I installed retriever as part of a full package including the GUI, though.  Maybe that’s what’s going on?

Shouldn't be. All installs include the GUI. Can you change the path in `connections.config` and see if the resulting file moves accordingly?

**Comment by davharris** [comment]
New path in connections.config is `SQLite,{'table_name': '{db}_{table}', 'file': '/Users/davidjharris/projects/sqlite.db’}`.

Still goes to the desktop.  Very mysterious.

**Comment by davharris** [comment]
It gets weirder.

I opened the GUI to change the path for sqlite manually.

It already showed the updated path, but I clicked through and hit “OK.”

Then I ran it again, and it put it in my projects folder.

Now it *always* puts it in the projects folder when I run retriever install sqlite mcdb.

**Comment by ethanwhite** [comment]
>  Very mysterious.

Indeed it is.

If you have Python installed can you open it up and run

```
import platform
platform.platform().lower()
```

and post the results.

**Comment by davharris** [comment]
'darwin-14.3.0-x86_64-i386-64bit'

**Comment by ethanwhite** [comment]
OK, got it. So, the reason this is happening is... complicated.

1. For Windows machines that are running the GUI the working directory is a system path where no one would ever look.
2. To fix this we initially had the retriever default to using the Desktop on Windows in all cases. This was a bad idea when using both the CLI and the R package because it resulted in the kind of confusion you've been suffering through (sorry about that). So we fixed it, first in `ecoretriever` https://github.com/ropensci/ecoretriever/pull/45 and then in the core `retriever` https://github.com/weecology/retriever/commit/5267d2651e3ef290cc33e3d51c10d683ae2c70eb, but neither of these are in the current releases.
3. By now your wondering why I keep telling you about Windows. Well, the way we've been checking the operating system is to look for the presence of `win` in the `platform.platform.lower()`, which was working great until Apple code named a release `darwin`. So, the retriever thinks you're on a Windows machine.

With that long winded explanation out of the way, the take home message for you is that with the next release of either `ecoretriever` or `retriever` this will all be working properly. Thanks a ton for reporting this and for working with me to figure it out. I'll be opening a new issue in the main retriever repo to deal with our Windows check.

**Comment by davharris** [comment]
Wow.  So basically it boils down to [this issue](http://www.pcworld.com/article/2690724/why-windows-10-isnt-named-9-windows-95-legacy-code.html).

Thanks again for working with me on this.

**Comment by ethanwhite** [comment]
At least I'm not the only one :)
