### ISSUE TITLE
R core suggest explicit import of read.csv and read.table from pkg utils

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/ecoretriever#58]
Hey @karthik @sckott. I just got a cran error report back and they found the following note:

```
* checking R code for possible problems ... NOTE
fetch: no visible global function definition for 'read.csv'
install: no visible global function definition for 'read.table'
Undefined global functions or variables:
  read.csv read.table
Consider adding
  importFrom("utils", "read.csv", "read.table")
to your NAMESPACE. 
```

I can't reproduce this note using R CMD check --as-cran so I'm not exactly what is going on. Also doesn't it seem strange that I would have to explicitly import functions from the utils package? My thought was just to go to the two places these functions are called and use the `::` operator. If you have any insight or advice here I'd appreciate it.

Thanks!

**Comment by gavinsimpson** [comment]
This is due to `r-devel` not the current `r-release` version and I suspect you didn't check against the former (or a recent enough build of the former).

Basically, when `R CMD check` does its thing (from `r-devel` onwards) it does so in an environment where only the base R functions are exported. Non of the other packages are available at the point of checking. Hence the request to explicit import functions from standard R pkgs shipped with R that previously you've not needed too.

This is good practice; if you rely on a function being available and not explicitly imported from a stated package, there is no guarantee at run time that a user will have the `read.csv()` that you were looking for.

At this point, consider the base packages shipped with as if they were any other packages and import the relevant functions.

Doing the import at run time via `::` is a little less efficient but can make sense if you only have one or two instances of such function calls in a package.

**Comment by sckott** [comment]
what @gavinsimpson said

**Comment by dmcglinn** [comment]
Thanks for the great explanation @gavinsimpson!  Should I also place `imports: utils` in the `DESCRIPTION` file?

**Comment by gavinsimpson** [comment]
@dmcglinn It appears not to be required, which is just plain confusing. I just added it whilst doing the same update to one of my packages (as the instructions are not clear one way or the other in WRE etc). Jari Oksanen then mentioned to me that you don;t need this in `DESCRIPTION` and `r-devel` doesn't seem to throw a fit if you leave it off. It might be worth soliciting input from the r-pkg-devel list as to this requirement if you want to be doubly sure.

**Comment by dmcglinn** [comment]
Sounds good thanks again!

**Comment by sckott** [comment]
FWIW, i now put used base pkgs in imports in `DESCRIPTION` - not clear what disadvantage there is, and it does make deps explicit

**Comment by gavinsimpson** [comment]
@sckott Agreed (which is why I haven't done what Jari suggested) and some of my packages have long depended on stats and graphics at the suggestion of Kurt many moons ago. Doing so certainly doesn't throw any additional errors/warnings or nags from `R CMD check`.

I'm with you on this one.

**Comment by sckott** [comment]
:+1:
